# -*- coding: utf-8 -*-
"""快速排序.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HToaFrXtnlS31XCjl6qNScfX5lUMp23I
"""

def quicksort(array, start, end):
  if start>=end:
    return
  pivot_index=start
  pivot=array[pivot_index]
  left=start
  right=end
  print(f"排序區間:{array[start:end+1]}，pivot={pivot}")
  while left!=right:
    while array[right]>=pivot and left!=right:
      right-=1
    while array[left]<=pivot and left!=right:
      left+=1
    if left!=right:
      array[left], array[right] = array[right], array[left]
      print(f"交換:{array[left]}和{array[right]}→{array}")
  if array[left]<array[pivot_index]:
      array[start], array[left]=array[left], array[start]
      print(f"交換pivot:{array[start]}和{array[left]}→{array}")
      pivot_index = left
  quicksort(array, start, pivot_index-1)
  quicksort(array, pivot_index+1, end)
data = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]
print("原始資料:", data)
quicksort(data, 0, len(data)-1)
print("排序後結果:", data)